"""Collector for Clang-Tidy and Clang Static Analyzer checks.

Scrapes the official clang-tidy checks list:
  https://clang.llvm.org/extra/clang-tidy/checks/list.html

This page lists ALL clang-tidy checks (~650) across every category:
abseil, altera, android, boost, bugprone, cert, clang-analyzer, concurrency,
cppcoreguidelines, darwin, fuchsia, google, linuxkernel, llvm, llvmlibc,
misc, modernize, mpi, objc, openmp, performance, portability, readability.

The "clang-analyzer-*" entries are the Clang Static Analyzer checkers
surfaced through the clang-tidy interface; the remaining categories are
pure clang-tidy lint checks.

Each check appears in a <table> row with:
  <a class="reference internal" href="category/name.html">
    <span class="doc">category-name</span>
  </a>
  <td> "Yes" if it offers fixes </td>

The page is generated by Sphinx and uses a toctree; the <span class="doc">
entries are the canonical check names.  Some appear multiple times due to
toctree rendering, so we deduplicate.
"""

import logging
import re
import html as html_mod

import requests

from .base import BaseCollector

logger = logging.getLogger(__name__)

CHECKS_URL = "https://clang.llvm.org/extra/clang-tidy/checks/list.html"
BASE_URL = "https://clang.llvm.org/extra/clang-tidy/checks/"
REQUEST_TIMEOUT = 60

# Map check category (prefix before first "-") → normalized category
CATEGORY_MAP = {
    "abseil": "style",
    "altera": "fpga",
    "android": "portability",
    "boost": "style",
    "bugprone": "correctness",
    "cert": "security",
    "clang": "memory-safety",       # clang-analyzer.*
    "concurrency": "concurrency",
    "cppcoreguidelines": "style",
    "darwin": "portability",
    "fuchsia": "style",
    "google": "style",
    "linuxkernel": "portability",
    "llvm": "style",
    "llvmlibc": "style",
    "misc": "misc",
    "modernize": "modernize",
    "mpi": "mpi",
    "objc": "objc",
    "openmp": "openmp",
    "performance": "performance",
    "portability": "portability",
    "readability": "readability",
}

# Checks in these categories are security-relevant
SECURITY_CATEGORIES = {"cert", "clang", "bugprone"}

# Hints for higher-severity checks (checked against lowercased name)
HIGH_SEVERITY_HINTS = [
    "nulldereference", "useafterfree", "use-after-free", "doublefree",
    "double-free", "stackaddress", "uninitialized", "bufferoverflow",
    "integeroverflow", "divisionbyzero", "mismatcheddeallocator",
    "insecureapi", "strcpy", "gets", "memcpy", "leak",
    "injection", "overflow", "taint", "useafterfree",
]


def _strip_tags(text):
    text = re.sub(r"<[^>]+>", " ", text)
    text = html_mod.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


class ClangCollector(BaseCollector):
    name = "clang"
    display_name = "Clang-Tidy"
    source_type = "web_scrape"
    source_url = CHECKS_URL
    description = (
        "Clang-Tidy is the Clang-based C++ linter that provides a unified "
        "framework for checking C/C++/Objective-C code for bugs, performance "
        "issues, style violations, and security vulnerabilities. It includes "
        "the Clang Static Analyzer checkers (surfaced as clang-analyzer-* "
        "checks) plus lint checks across abseil, altera, android, boost, "
        "bugprone, cert, cppcoreguidelines, google, llvm, misc, modernize, "
        "performance, readability, and other categories."
    )
    logo_url = "https://avatars.githubusercontent.com/u/1507452"

    def collect_rules(self):
        logger.info(f"[clang] Fetching clang-tidy checks from {CHECKS_URL}...")
        resp = requests.get(CHECKS_URL, timeout=REQUEST_TIMEOUT)
        resp.raise_for_status()
        html = resp.text

        # Each check appears as:
        #   <a class="reference internal" href="category/name.html">
        #     <span class="doc">category-name</span></a>
        # Extract href + check name pairs, deduplicate by check name.
        pairs = re.findall(
            r'href="([^"]+)"[^>]*><span class="doc">([^<]+)</span>',
            html,
        )

        seen = set()
        count = 0

        for href, check_name in pairs:
            check_name = _strip_tags(check_name)
            if not check_name or check_name in seen:
                continue
            seen.add(check_name)

            # Derive category from the check name prefix (before first "-")
            # e.g. "bugprone-argument-comment" → "bugprone"
            #      "clang-analyzer-core.NullDereference" → "clang"
            category_prefix = check_name.split("-")[0]
            category = CATEGORY_MAP.get(category_prefix, "misc")

            # Build the full URL to the individual check page
            if href.startswith("http"):
                check_url = href
            else:
                check_url = BASE_URL + href

            # Determine severity
            low_name = check_name.lower()
            if category_prefix in SECURITY_CATEGORIES or any(
                h in low_name for h in HIGH_SEVERITY_HINTS
            ):
                severity = "high"
            elif category_prefix in ("performance", "modernize", "readability"):
                severity = "low"
            else:
                severity = "medium"

            # Build a human-readable title from the check name
            # e.g. "bugprone-argument-comment" → "Bugprone Argument Comment"
            title = check_name.replace("-", " ").replace(".", " ").title()

            tags = [category_prefix, category]
            if "clang-analyzer" in check_name:
                tags.append("static-analyzer")

            self.upsert(
                rule_id=check_name,
                title=title,
                description="",
                severity=severity,
                category=category,
                language="c,c++,objc",
                cwe_ids=[],
                owasp_ids=[],
                tags=tags,
                source_file=check_url,
                rule_content="",
                rule_format="html",
                metadata={
                    "category_prefix": category_prefix,
                    "check_name": check_name,
                    "url": check_url,
                    "source": "clang.llvm.org/clang-tidy",
                },
            )
            count += 1

        logger.info(f"[clang] Collected {count} checks.")
        return self.stats